<?php /* @var $block \Bitbull\Tooso\Block\Adminhtml\System\AbstractButton */ ?>

<script>
    require([
        'jquery',
        'prototype'
    ], function($){

        var buttonId = "<?php echo $block->getButtonId() ?>";
        var collectSpan = $('#'+buttonId+'_span');

        $('#'+buttonId).click(function () {
            var button = $(this);

            new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
                parameters:     {},
                loaderArea:     false,
                asynchronous:   true,
                onCreate: function() {
                    collectSpan.find('.done').hide();
                    collectSpan.find('.error').hide();
                    collectSpan.find('.processing').show();
                    collectSpan.find('.message_span').text('');
                    button.prop("disabled",true);
                },
                onSuccess: function(response) {
                    collectSpan.find('.processing').hide();
                    button.prop("disabled",false);
                    if (response.status === 200) {
                        collectSpan.find('.done').show();
                        if (response.responseJSON && response.responseJSON.contentToDownload) {
                            var myBlob = new Blob([response.responseJSON.contentToDownload.toString()], {type: "plain/text"});
                            window.location = URL.createObjectURL(myBlob);
                        }
                    }
                    setTimeout(function () {
                        collectSpan.find('.done').hide();
                    }, 3000)
                },
                onFailure: function(response) {
                    button.prop("disabled",false);
                    collectSpan.find('.processing').hide();
                    collectSpan.find('.error').show();
                    collectSpan.find('.message_span').text(response.statusText);
                    setTimeout(function () {
                        collectSpan.find('.message_span').text('');
                        collectSpan.find('.error').hide();
                    }, 3000)
                }
            });
        });

    });
</script>

<?php echo $block->getButtonHtml() ?>
<span id="<?php echo $block->getButtonId() ?>_span">
    <img class="processing" alt="Loading" style="margin:0 5px; display: none;" src="<?php echo $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
    <img class="done" alt="Done" style="margin:-3px 5px; display: none;" src="<?php echo $block->getViewFileUrl('images/rule_component_apply.gif') ?>"/>
    <img class="error" alt="Error" style="margin:-3px 5px; display: none;" src="<?php echo $block->getViewFileUrl('images/rule_component_remove.gif') ?>"/>
    <span class="message_span"></span>
</span>
