<?php

/** @var \Tooso\SDK\Search\Result $searchData */
$searchResult = $block->search->getResult();
$searchId = null;
$searchData = null;
if ($searchResult !== null) {
    $searchId = $searchResult->getSearchId();
    $searchData = $searchResult->getResponse();
}
?>

<?php if ($block->config->isDebugModeEnabled()): ?>
<script id="tooso-search-debug">
    console.debug('search id: <?=$searchId ?: 'not set'?>');
    console.debug('search data:', <?=$searchData ? json_encode($searchData) : "'not set'"?>);
</script>
<?php endif; ?>

<script id="<?=$block->getScriptId()?>"></script>
