<?php
/** @var \Bitbull\Tooso\Block\Tracking\Library $block */
$libraryEndpoint = $block->getLibraryEndpoint();
?>

<script type="text/javascript">
    require([], function(){
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s);
            js.id = id;
            js.src = "<?=$libraryEndpoint?>";
            js.async = true;
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', '<?=$block->getScriptId()?>'));
    });
</script>

